name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: build, test, publish
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      # Why not using setup-node 2.2+ cache option (yet) ?
      # see https://github.com/belgattitude/nextjs-monorepo-example/pull/369
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Typecheck
        run: |
          yarn typecheck

      - name: Tests
        run: |
          yarn test
        env:
          CI: true

      - name: Potentially save npm token
        run: |
          ([[ ! -z ${{ secrets.NPM_TOKEN }} ]] && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc) || echo "Did not write npm token"
      - name: Potentially publish canary to npm
        run: |
          if \
            ls ~/.npmrc >/dev/null 2>&1 && \
            [[ $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn run lerna publish from-git --npm-tag canary --yes
          else
            echo "Did not publish canary"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY_BYPASS: true
      - name: Potentially publish stable to npm
        run: |
          if \
            ls ~/.npmrc >/dev/null 2>&1 && \
            [[ ! $(git describe --exact-match 2> /dev/null || :) =~ -canary ]]; \
          then
            yarn run lerna publish from-git --yes
          else
            echo "Did not publish"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY_BYPASS: true
